load("@rules_qt//:qt.bzl", "qt_resource_via_qrc")

qt_resource_via_qrc(
    name = "resources_qrc",
    files = [
        "images/copy.png",
        "images/cut.png",
        "images/paste.png",
        "images/save.png",
        "images/open.png",
        "images/new.png",
    ],
    qrc_file = "resources.qrc",
    visibility = ["//visibility:public"],
)