load("@rules_qt//:qt.bzl", "qt_resource_via_qrc")

qt_resource_via_qrc(
    name = "clients_qrc",
    files = ["clients.txt"],
    qrc_file = "resources.qrc",
    visibility = ["//visibility:public"],
)